/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaz;

import Logica.construccion;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author NATA
 */
public class Inicio extends javax.swing.JFrame {
    
    construccion con = new construccion();
    String resp;
    Respuesta resultado;
    
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Logo.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTPContenido = new javax.swing.JTabbedPane();
        JPNuevo = new javax.swing.JPanel();
        JLTextoNuevo = new javax.swing.JLabel();
        JLTextoNuevo1 = new javax.swing.JLabel();
        JLEjemplo = new javax.swing.JLabel();
        JTFNuevo = new javax.swing.JTextField();
        JBCrearNuevo = new javax.swing.JButton();
        JPInPre = new javax.swing.JPanel();
        JLTextoPre = new javax.swing.JLabel();
        JLTextoPre1 = new javax.swing.JLabel();
        JTFRPreorden = new javax.swing.JTextField();
        JTFRInortenPRE = new javax.swing.JTextField();
        JBCrearInPre = new javax.swing.JButton();
        JPInPos = new javax.swing.JPanel();
        JLTextoPos = new javax.swing.JLabel();
        JTFRPosorden = new javax.swing.JTextField();
        JLTextoPos1 = new javax.swing.JLabel();
        JTFRInortenPos = new javax.swing.JTextField();
        JBCrearInPos = new javax.swing.JButton();
        JBSalir = new javax.swing.JButton();
        JBLimpiar = new javax.swing.JButton();
        JLEncabezado = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arboles");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(300, 100, 480, 460));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Inicio"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        JTPContenido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JLTextoNuevo.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        JLTextoNuevo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLTextoNuevo.setText("Ingrese la lista de datos que desea poner en el árbol, separado");

        JLTextoNuevo1.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        JLTextoNuevo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLTextoNuevo1.setText("por comas:");

        JLEjemplo.setText("Ejemplo: 8,12,6,4,3");

        JTFNuevo.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N

        JBCrearNuevo.setText("Crear");
        JBCrearNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCrearNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPNuevoLayout = new javax.swing.GroupLayout(JPNuevo);
        JPNuevo.setLayout(JPNuevoLayout);
        JPNuevoLayout.setHorizontalGroup(
            JPNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLTextoNuevo)
                    .addComponent(JLTextoNuevo1)
                    .addGroup(JPNuevoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(JPNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLEjemplo)
                            .addComponent(JTFNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNuevoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBCrearNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        JPNuevoLayout.setVerticalGroup(
            JPNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNuevoLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(JLTextoNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLTextoNuevo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLEjemplo)
                .addGap(18, 18, 18)
                .addComponent(JTFNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(JBCrearNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        JTPContenido.addTab("Nuevo", JPNuevo);

        JLTextoPre.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        JLTextoPre.setText("Ingrese el recorrido en Preorden:");

        JLTextoPre1.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        JLTextoPre1.setText("Ingrese el recorrido en Inorden:");

        JTFRPreorden.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N

        JTFRInortenPRE.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N

        JBCrearInPre.setText("Crear");
        JBCrearInPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCrearInPreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPInPreLayout = new javax.swing.GroupLayout(JPInPre);
        JPInPre.setLayout(JPInPreLayout);
        JPInPreLayout.setHorizontalGroup(
            JPInPreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPInPreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPInPreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JTFRInortenPRE, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPInPreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JLTextoPre1)
                        .addComponent(JLTextoPre)
                        .addGroup(JPInPreLayout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(JTFRPreorden, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPInPreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBCrearInPre, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        JPInPreLayout.setVerticalGroup(
            JPInPreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPInPreLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(JLTextoPre)
                .addGap(18, 18, 18)
                .addComponent(JTFRPreorden, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(JLTextoPre1)
                .addGap(18, 18, 18)
                .addComponent(JTFRInortenPRE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(JBCrearInPre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        JTPContenido.addTab("Inorden-Preorden", JPInPre);

        JLTextoPos.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        JLTextoPos.setText("Ingrese el recorrido en Posorden:");

        JTFRPosorden.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N

        JLTextoPos1.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        JLTextoPos1.setText("Ingrese el recorrido en Inorden:");

        JTFRInortenPos.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N

        JBCrearInPos.setText("Crear");
        JBCrearInPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCrearInPosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPInPosLayout = new javax.swing.GroupLayout(JPInPos);
        JPInPos.setLayout(JPInPosLayout);
        JPInPosLayout.setHorizontalGroup(
            JPInPosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPInPosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPInPosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JTFRInortenPos, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPInPosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JLTextoPos1)
                        .addComponent(JLTextoPos)
                        .addGroup(JPInPosLayout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(JTFRPosorden, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPInPosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBCrearInPos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        JPInPosLayout.setVerticalGroup(
            JPInPosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPInPosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(JLTextoPos)
                .addGap(18, 18, 18)
                .addComponent(JTFRPosorden, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(JLTextoPos1)
                .addGap(18, 18, 18)
                .addComponent(JTFRInortenPos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(JBCrearInPos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        JTPContenido.addTab("Inorden-Posorden", JPInPos);

        JBSalir.setText("Salir");
        JBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalirActionPerformed(evt);
            }
        });

        JBLimpiar.setText("Limpiar");
        JBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLimpiarActionPerformed(evt);
            }
        });

        JLEncabezado.setText("Arboles");

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JTPContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTPContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLimpiarActionPerformed
        // TODO add your handling code here:
        con.eliminar();
        JTFNuevo.setText(null);
        JTFRInortenPRE.setText(null);
        JTFRInortenPos.setText(null);
        JTFRPosorden.setText(null);
        JTFRPreorden.setText(null);
        //System.out.println("limpiado");
    }//GEN-LAST:event_JBLimpiarActionPerformed

    private void JBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JBSalirActionPerformed

    private void JBCrearNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCrearNuevoActionPerformed
        // TODO add your handling code here:
        //System.out.println(JTFNuevo.getText());
        resp = con.construccionCero(JTFNuevo.getText());
        if(resp!=null){
            JOptionPane.showMessageDialog(null, resp, "Error", 1);
        }else{
            resultado = new Respuesta();
            resultado.pintarResultado(con);
            resultado.setVisible(true);
        }
        
    }//GEN-LAST:event_JBCrearNuevoActionPerformed

    private void JBCrearInPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCrearInPreActionPerformed
        // TODO add your handling code here:
        //System.out.println("in: "+JTFRInortenPRE.getText());
        //System.out.println("pre: "+JTFRPreorden.getText());
        resp = con.recInPre(JTFRInortenPRE.getText(), JTFRPreorden.getText());
        if(resp!=null){
            JOptionPane.showMessageDialog(null, resp, "Error", 1);
        }else{
            resultado = new Respuesta();
            resultado.pintarResultado(con);
            resultado.setVisible(true);
        }
    }//GEN-LAST:event_JBCrearInPreActionPerformed

    private void JBCrearInPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCrearInPosActionPerformed
        // TODO add your handling code here:
        //System.out.println("in: "+JTFRInortenPos.getText());
        //System.out.println("pos: "+JTFRPosorden.getText());
        resp = con.recInPos(JTFRInortenPos.getText(), JTFRPosorden.getText());
        if(resp!=null){
            JOptionPane.showMessageDialog(null, resp, "Error", 1);
        }else{
            resultado = new Respuesta();
            resultado.pintarResultado(con);
            resultado.setVisible(true);
        }
    }//GEN-LAST:event_JBCrearInPosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCrearInPos;
    private javax.swing.JButton JBCrearInPre;
    private javax.swing.JButton JBCrearNuevo;
    private javax.swing.JButton JBLimpiar;
    private javax.swing.JButton JBSalir;
    private javax.swing.JLabel JLEjemplo;
    private javax.swing.JLabel JLEncabezado;
    private javax.swing.JLabel JLTextoNuevo;
    private javax.swing.JLabel JLTextoNuevo1;
    private javax.swing.JLabel JLTextoPos;
    private javax.swing.JLabel JLTextoPos1;
    private javax.swing.JLabel JLTextoPre;
    private javax.swing.JLabel JLTextoPre1;
    private javax.swing.JPanel JPInPos;
    private javax.swing.JPanel JPInPre;
    private javax.swing.JPanel JPNuevo;
    private javax.swing.JTextField JTFNuevo;
    private javax.swing.JTextField JTFRInortenPRE;
    private javax.swing.JTextField JTFRInortenPos;
    private javax.swing.JTextField JTFRPosorden;
    private javax.swing.JTextField JTFRPreorden;
    private javax.swing.JTabbedPane JTPContenido;
    private javax.swing.JLabel Logo;
    // End of variables declaration//GEN-END:variables
}
