/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaz;

import Logica.construccion;
import java.awt.BorderLayout;
import java.awt.Rectangle;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;

/**
 *
 * @author NATA
 */
public class Respuesta extends javax.swing.JFrame {
    
    construccion Arbol;
    String recInorden;
    String recPreorden;
    String recPosorden;
    double sumaTotal;
    double sumaTres;
    
    /**
     * Creates new form Respuesta
     */
    public Respuesta() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Logo.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        JBInorden = new javax.swing.JButton();
        JBPosorden = new javax.swing.JButton();
        JLSumaT = new javax.swing.JLabel();
        JBPreorden = new javax.swing.JButton();
        JLSumaTres = new javax.swing.JLabel();
        JLRespuestaST = new javax.swing.JLabel();
        JLRespuestaSMT = new javax.swing.JLabel();
        JLRecorrido = new javax.swing.JLabel();
        JLNombreR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Arbol");
        setBounds(new java.awt.Rectangle(350, 25, 700, 600));
        setResizable(false);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JBInorden.setText("Inorden");
        JBInorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBInordenActionPerformed(evt);
            }
        });

        JBPosorden.setText("Posorden");
        JBPosorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPosordenActionPerformed(evt);
            }
        });

        JLSumaT.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        JLSumaT.setText("Suma de los elementos:");

        JBPreorden.setText("Preorden");
        JBPreorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPreordenActionPerformed(evt);
            }
        });

        JLSumaTres.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        JLSumaTres.setText("Suma de los multiplos de 3:");

        JLRespuestaST.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        JLRespuestaST.setText("Respuesta");

        JLRespuestaSMT.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        JLRespuestaSMT.setText("Respuesta");

        JLRecorrido.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        JLRecorrido.setText("Recorrido");

        JLNombreR.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        JLNombreR.setText("Nombre recorrido:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLRespuestaSMT, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLRespuestaST, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JLSumaT)
                        .addComponent(JLSumaTres)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBPreorden, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBPosorden, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBInorden, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLNombreR, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(JLRecorrido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLSumaT)
                            .addComponent(JLNombreR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLRespuestaST)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JLSumaTres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JLRespuestaSMT))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBInorden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBPreorden)
                            .addComponent(JLRecorrido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBPosorden)))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBInordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBInordenActionPerformed
        // TODO add your handling code here:
        this.JLNombreR.setText("Recorrido Inorden:");
        this.JLRecorrido.setText(recInorden);
    }//GEN-LAST:event_JBInordenActionPerformed

    private void JBPreordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPreordenActionPerformed
        // TODO add your handling code here:
        this.JLNombreR.setText("Recorrido Preorden:");
        this.JLRecorrido.setText(recPreorden);
    }//GEN-LAST:event_JBPreordenActionPerformed

    private void JBPosordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPosordenActionPerformed
        // TODO add your handling code here:
        this.JLNombreR.setText("Recorrido Posorden:");
        this.JLRecorrido.setText(recPosorden);
    }//GEN-LAST:event_JBPosordenActionPerformed

    public void pintarResultado(construccion arbol){
        this.Arbol = arbol;
        this.recInorden = Arbol.construirListaInorden(Arbol.getCab());
        this.recPreorden = Arbol.construirListaPreorden(Arbol.getCab());
        this.recPosorden = Arbol.construirListaPosorden(Arbol.getCab());
        this.sumaTotal = Arbol.sumaElementos(recInorden);
        this.sumaTres = Arbol.sumaTres(recInorden);
        
        this.jDesktopPane1.removeAll();
        Rectangle tamaño = this.jInternalFrame1.getBounds();
        this.jInternalFrame1 = null;
        this.jInternalFrame1 = new JInternalFrame("Representación gráfica", true);
        this.jDesktopPane1.add(this.jInternalFrame1, JLayeredPane.DEFAULT_LAYER);
        this.jInternalFrame1.setVisible(true);
        this.jInternalFrame1.setBounds(tamaño);
        this.jInternalFrame1.setEnabled(true);
        this.jInternalFrame1.add(Arbol.Pintar(), BorderLayout.CENTER);
        
        this.JLRespuestaST.setText(String.valueOf((long) sumaTotal));
        this.JLRespuestaSMT.setText(String.valueOf((long) sumaTres));
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Respuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Respuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Respuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Respuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Respuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBInorden;
    private javax.swing.JButton JBPosorden;
    private javax.swing.JButton JBPreorden;
    private javax.swing.JLabel JLNombreR;
    private javax.swing.JLabel JLRecorrido;
    private javax.swing.JLabel JLRespuestaSMT;
    private javax.swing.JLabel JLRespuestaST;
    private javax.swing.JLabel JLSumaT;
    private javax.swing.JLabel JLSumaTres;
    private javax.swing.JPanel jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    // End of variables declaration//GEN-END:variables
}
