/* Generated By:JavaCC: Do not edit this line. factorialConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface factorialConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 1;
  /** RegularExpression Id. */
  int NUMBER = 2;
  /** RegularExpression Id. */
  int IDENTIFIER = 3;
  /** RegularExpression Id. */
  int PI = 4;
  /** RegularExpression Id. */
  int IGUAL = 5;
  /** RegularExpression Id. */
  int INCR = 6;
  /** RegularExpression Id. */
  int CLASE = 7;
  /** RegularExpression Id. */
  int FOR = 8;
  /** RegularExpression Id. */
  int PUBLIC = 9;
  /** RegularExpression Id. */
  int RETURN = 10;
  /** RegularExpression Id. */
  int LP = 11;
  /** RegularExpression Id. */
  int RP = 12;
  /** RegularExpression Id. */
  int LB = 13;
  /** RegularExpression Id. */
  int RB = 14;
  /** RegularExpression Id. */
  int SEMICOLON = 15;
  /** RegularExpression Id. */
  int LE = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"int\"",
    "<NUMBER>",
    "<IDENTIFIER>",
    "\"*=\"",
    "\"= \"",
    "\"++\"",
    "\"class \"",
    "\"for \"",
    "\"public \"",
    "\"return \"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"<=\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
